### ISSUE TITLE
TRACK method (v2) response validation bug

### ISSUE THREAD

**Issue by david-vaclavek** [inspirum/balikobot-php#1]
## Detailed description

While trying to get a response in "trackPackage" method in "Client" class, an error is returned, even though there is a valid data returned. It is caused by statusCode set to 500.

## Context

Fixes the bug. Allows users to retrieve relevant data.

## Possible implementation

There is supposed to be $shouldHaveStatus variable in validateResponseStatus method set to false as there is not this index set in the response.
Just set shouldHaveStatus parameter in the trackPackage method to false - this solves the problem.

## Your environment
Not necessary

**Comment by tomas-novotny** [comment]
Fixed with adding `$shouldHaveStatus = false` in `trackPackage` method.

Resolved in [v1.1.2](https://github.com/inspirum/balikobot-php/tree/v1.1.2)
