### ISSUE TITLE
trackPackages throws TypeError

### ISSUE THREAD

**Issue by eugeene** [inspirum/balikobot-php#11]
method trackPackages throws TypeError

Provide a detailed description of the change or addition you are proposing.

Probably a bug

## Context

To make it work

How can it benefit other users?

It will work for them

Not obligatory, but suggest an idea for implementing addition or change.

cheheck if $status variable in trackPackages' method's loop is array
 
PHP7.4
inspirum/balikobot composer version 3.3.0

Sometimes when trackPackages() method is called, we got this error:

**Argument 1 passed to Inspirum\Balikobot\Model\Values\PackageStatus::newInstanceFromData() must be of the type array, string given**

I am unable to replicate this error in testing environment, but live, the error sometimes appear for us.

**Comment by eugeene** [comment]
when I update to latest 5.1 version, the variable ServiceType::ZASILKOVNA (formerly null) is not available anymore. Can you tell me what is the substitution for that?

**Comment by tomas-novotny** [comment]
From major version [v4.0.0](https://github.com/inspirum/balikobot-php/releases/tag/v4.0.0), this API uses **v2** for Zasilkova **ADD** request (see https://balikobot.docs.apiary.io/#reference/add/add-zasilkovna-v2) which uses `servise_type` constants. For example `ServiceType::ZASILKOVNA_VMCZ` (https://github.com/inspirum/balikobot-php/blob/master/src/Definitions/ServiceType.php#L748)

I also couldn't replicate error (problem with test credentials is that API returns correct dummy data for any input), but I think that additional validation (https://github.com/inspirum/balikobot-php/blob/master/src/Services/Formatter.php#L65) and APIv2 response format fixed this issue.

Please check if this problem happens in newest version. If it does, please provide full API response to debug. 
Thank you

**Comment by eugeene** [comment]
Thank you for responding. We've already migrated to the latest version of inspirum/balikobot, so everything should be fine.
