### ISSUE TITLE
Branches not in Shipper::hasBranchCountryFilterSupport are not filtered by country on api level

### ISSUE THREAD

**Issue by Dukecz** [inspirum/balikobot-php#12]
## Detailed description

Balikobot branches allows filtering results by either country or service for shippers not in `\Inspirum\Balikobot\Definitions\Shipper::hasBranchCountryFilterSupport`. (https://balikobotv2.docs.apiary.io/#reference/branches) but `\Inspirum\Balikobot\Services\Balikobot::getAllBranchesForShipperServiceForCountries` filters only by service:

https://github.com/inspirum/balikobot-php/blob/v5.3.0/src/Services/Balikobot.php#L467

## Context

This is a problem especially for Zasilkovna with $service set as null, because the countries are filtered later and it requires excessive amount of memory.

Calling `$shipper/branches/country/$country` would greatly reduce the response size and allowed to remove filtering by countries later.

## Possible implementation

`\Inspirum\Balikobot\Definitions\Shipper::hasBranchCountryFilterSupport` should only be checked in case both $service and $country is set. Or the check can be dropped completely in favor of api exception in response.

## Your environment

inspirum/balikobot: v5.3.0

**Comment by tomas-novotny** [comment]
You are right, shipper without _branch country filter support_ can filter by country if `$serviceType` is `null`.

It have been solved in [v5.4.0](https://github.com/inspirum/balikobot-php/releases/tag/v5.4.0) by commit [2096894](https://github.com/inspirum/balikobot-php/commit/2096894e140b1a748012d8ff6b9365e218d9e4f6)

**Comment by Dukecz** [comment]
Thanks for the quick reaction. Fix works well.
