### ISSUE TITLE
Client::getAddServiceOptions without service doesnt return any data

### ISSUE THREAD

**Issue by Dukecz** [inspirum/balikobot-php#13]
## Detailed description

`\Inspirum\Balikobot\Services\Client::getAddServiceOptions` called without service returns empty array.

Without serviceType the api returns options nested for all services under service_types key:

```json
{
    "status": 200,
    "service_types": [
        {
            "service_type": "F",
            "service_type_name": "Fofr",
            "services": [
                {
                    "code": 1,
                    "name": "křehké"
                },
                {
                    "code": 2,
                    "name": "neklopit"
                },
                {
                    "code": 3,
                    "name": "deštník"
                },
                {
                    "code": 4,
                    "name": "SMS před svozem"
                },
                {
                    "code": 5,
                    "name": "SMS před doručením"
                }
            ]
        }
    ]
}
```
...

## Your environment

inspirum/balikobot: v5.4.0

**Comment by tomas-novotny** [comment]
Thank you for reporting this issue.

It have been solved in [v5.4.1](https://github.com/inspirum/balikobot-php/releases/tag/v5.4.1) by commit [440314e](https://github.com/inspirum/balikobot-php/commit/440314ec6ce6d0d7cfc3ab99d7c0a7656971b6af)
