### ISSUE TITLE
Balikobot::trackPackage chybně detekuje 404 české pošty jako Nedoručený balík

### ISSUE THREAD

**Issue by josefbenjac** [inspirum/balikobot-php#15]
Tracking api **Balíkobotu** vrací v určitých případech české pošty zvláštní odpověď, kde je namísto pole eventů, pouze pole se stringem `404` .

```json
{
	"packages": [
		{
			"carrier_id": "NBxxxxxxxxxxxxxx",
			"status": 200,
			"states": ["404"]
		}
	]
}	
```

Z **Balíkobotu** máme vyjádření, že pouze přeposílají data z České Pošty a tudíž se tomu nebudou věnovat.

Na základě této chyby, knihovna špatně detekuje stav **4 - Nedoručený balík**. 

![image](https://user-images.githubusercontent.com/6731626/126319185-8b9760d3-c0b9-466b-ae72-7b4070a9e562.png)

Toto se dá jednoduše **hacknout** na straně použití knihovny přibližně takto: 

```php
$statuses = $this->balikobot->trackPackage($orderedPackage);

// Hack / fix 404 Czech Post in Inspirum library
if (
	$package->getShipper()->isCeskaPosta()
	&& count($statuses) === 1
	&& $statuses[0]->getId() === 4.0
	&& $statuses[0]->getName() === '4'
	&& $statuses[0]->getDescription() === '4'
	&& $statuses[0]->getDate() === null
) {
	$statuses = [];
}
```

Nicméně bylo by moc fajn, kdyby toto uměla řešit **přímo knihovna**. 

Díky za váš čas, pokud se tomu budete věnovat.

**Comment by tomas-novotny** [comment]
Zdravím,

Pro PHP 8.0+ knihovna "správně" spadla, jelikož již není možné přistupovat k textu jako k poli (`Error: Cannot access offset of type string on string`)

Opraveno [386c988](https://github.com/inspirum/balikobot-php/commit/386c988481df80c328a7e11feed737a2bfe91da8) – nyní bude tyto stavy knihovna ignorovat.

Nový release včetně tohoto bugfixu bude po zpracovaní nových změn v dokumentaci Balikobot API.

**Comment by tomas-novotny** [comment]
It have been solved in [v5.5.0](https://github.com/inspirum/balikobot-php/releases/tag/v5.5.0)
