### ISSUE TITLE
The method resolveBranchId() generates wrong branchId for PPL

### ISSUE THREAD

**Issue by mz0lee** [inspirum/balikobot-php#18]
In some cases PPL branch ids contain the string 'KM' multiple times, wich than generates a faulty branchId property.

e.g. `KMSKMK000000000` -> `SK000000000`

I'm not sure why the leading 'KM' has to be removed but with the current str_replace method it's not sufficient for this purpose.
A more specific way would be to do it with preg_match().

**Comment by tomas-novotny** [comment]
Thank you for reporting this issue.

It have been solved in [v7.3.0](https://github.com/inspirum/balikobot-php/releases/tag/v7.3.0) by commit [de33b3a](https://github.com/inspirum/balikobot-php/commit/de33b3a24356ce0ec2a1f75c8653b055cf1edf8a).
