### ISSUE TITLE
Trackstatus is not available for \Inspirum\Balikobot\Definitions\API::V2V2

### ISSUE THREAD

**Issue by martinknor** [inspirum/balikobot-php#19]
`\Inspirum\Balikobot\Services\Client::trackPackagesLastStatus` call trackstatus with version V2V2, but in documentation it's not available - it's same as V2

see https://balikobot.docs.apiary.io/#reference/tracking/trackstatus-v2

I wrote with balikobot and they wrote:

![image](https://user-images.githubusercontent.com/2004222/232430017-bb7a967f-21ec-404e-b944-6f1765e74507.png)

**Comment by tomas-novotny** [comment]
Thank you for reporting this issue.

It have been solved in [v7.4.0](https://github.com/inspirum/balikobot-php/releases/tag/v7.4.0) by commit [2032939](https://github.com/inspirum/balikobot-php/commit/20329394e46ee32a1b8a7b34c913e3014d7d1550).

**Comment by tomas-novotny** [comment]
I have updated branches `5.x` and `6.x` to fix this bug. It have been solved in [v5.7.1](https://github.com/inspirum/balikobot-php/releases/tag/v5.7.1) and [v6.2.1](https://github.com/inspirum/balikobot-php/releases/tag/v6.2.1).
