### ISSUE TITLE
GLS sometimes returns bad response with HTTP code of 200

### ISSUE THREAD

**Issue by eugeene** [inspirum/balikobot-php#4]
From time to time, GLS sends valid HTTP 200 code response with just content of '**503**' - service not available. Which is correctly decoded by **json_decode**, but the result is not an array, thus fails to be passed onto next functions:

[25-Jun-2020 18:21:38 Europe/Prague] PHP Fatal error:  Uncaught TypeError: **Argument 1 passed to Inspirum\Balikobot\Model\Values\PackageStatus::newInstanceFromData() must be of the type array, string given, called in** /www/sites/7/site70717/public_html/vendor/inspirum/balikobot/src/Services/Balikobot.php on line 170 and defined in /www/sites/7/site70717/public_html/vendor/inspirum/balikobot/src/Model/Values/PackageStatus.php:68
Stack trace:
#0 /www/sites/7/site70717/public_html/vendor/inspirum/balikobot/src/Services/Balikobot.php(170): **Inspirum\Balikobot\Model\Values\PackageStatus::newInstanceFromData('503')**
#1 /www/sites/7/site70717/public_html/vendor/inspirum/balikobot/src/Services/Balikobot.php(146): Inspirum\Balikobot\Services\Balikobot->trackPackages(Object(Inspirum\Balikobot\Model\Aggregates\OrderedPackageCollection))
#2 /www/sites/7/site70717/public_html/cron/balikobotCheckStatus.php(40): Inspirum\Balikobot\Services\Balikobot->trackPackage(Object(Inspirum\Balikobot\Model\Values\OrderedPackage))
#3 {main}
  thrown in /www/sites/7/site70717/public_html/vendor/inspirum/balikobot/src/Model/Values/PackageStatus.php on line 68

## Possible implementation

**Definitely should be fixed on the side of GLS**. Will report this issue to them as well. Also reporting here just for information. Could be possibly fixed in library as well

**Comment by eugeene** [comment]
Official response from GLS:


Dobrý den,

o této chybě víme a od vývojářů máme informace že se pracuje na lepším reportování chyb. Bohužel termín kdy by to mělo být hotovo neznám.

Omlouváme se za komplikace a děkujeme za trpělivost.

 

Přeji krásný zbytek dne.

**Comment by tomas-novotny** [comment]
Only fix that can be done is validate that all response item (packages, statuses, ...) has necessary data.
Now there is only check that first item has it (like `if (isset($response[0]['package_id']) === false)`)

I submited PR #6 that partially fix this problem by throwing expected exception (`BadRequestException`), instead of `TypeError`. Will it be atleast somehow helpful? @eugeene 

Unfortunately for a real solution to this problem this has to be fix by GLS.
