### ISSUE TITLE
Track status v3

### ISSUE THREAD

**Issue by tomas-kulhanek** [inspirum/balikobot-php#9]
Ahoj, 
prosím jen informativně, je v plánu implmentovat i https://balikobot.docs.apiary.io/#reference/tracking/track-v3 ?

**Comment by tomas-novotny** [comment]
Zdravím,

Request TRACK v3 je implementován od verze v4.0.0:

https://github.com/inspirum/balikobot-php/blob/master/CHANGELOG.md#v400-2020-09-21
https://github.com/inspirum/balikobot-php/blob/v4.5.0/src/Services/Client.php#L126

V APIv2 (od verze v5.0.0)  je stejný request jako v2:

https://balikobotv2.docs.apiary.io/#reference/tracking/track-v2
https://github.com/inspirum/balikobot-php/blob/v5.0.0/src/Services/Client.php#L130

**Comment by tomas-kulhanek** [comment]
Aha, já jsem koukal na readme a tam je jen o v2. Ok, díky moc za odpověď.
